name: My First Workflows
on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome message
              run: |
                echo " Hello world from Github Actions"

            - name: Clone repository ${{ github.repository }}
              uses: actions/checkout@v6

            - name: List Files ${{ github.repository }}
              run: cd ${{ github.repository }}

            - name: Read file
              run: cat README.md