name: My First Workflows
on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Clone repository ${{ github.repository }}
              uses: actions/checkout@v6

            - name: Welcome message
              run: |
                echo " Hello world from Github Actions"
                ls -lrth
                cat README.md