name: Generate ASCII artwork with cowsay
on: push

jobs:
    ascii_artwork_job:
        runs-on: ubuntu-latest
        steps:
        - name: Clone repo
          uses: actions/checkout@v4

        - name: Install Cowsay Program
          run:  .chmod +x ascii-script.sh

        - name: Install Cowsay Program
          run:  ./ascii-script.sh

