name: Generate ASCII artwork with cowsay
on: push

jobs:
    ascii_artwork_job:
        runs-on: ubuntu-latest
        steps:
        - name: Clone repo
          uses: actions/checkout@v4
        
        - name: Install Cowsay Program
          run:  sudo apt-get install cowsay -y

        - name: Execute Cowsay CMD
          run:  cowsay -f lion "Run for cover, I am a LION OF TERANGA champions of AFRICA...GRURR" >> lion.txt

        - name: Test File Exists
          run:  grep -i "lion" lion.txt
        
        - name: Read File
          run:  cat lion.txt

        - name: List Repo Files
          run:  ls -lrtha
