name: Multiple Job Worklow
on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Install cowsay and Execute command
              run:  |
                echo "Install Cowsay Program"
                sudo apt-get install cowsay -y

                echo "Execute Cowsay CMD"
                cowsay -f dragon "Run for cover, I am a DRAGON...RAWR" >> dragon.txt
                sleep 30

    test:
        needs: build
        runs-on: ubuntu-latest
        steps: 
            - name: Sleep for 10 seconds and Test File existence
              run: | 
                sleep 10
                echo "Test File Exists"
                grep -i "dragon" dragon.txt
            
    deploy:
        needs: [test]
        runs-on: ubuntu-latest
        steps:
          - name: Sleep of 10 seconds
            run: |
              sleep 10
              echo "Read File"
              cat dragon.txt

              echo "List Repo Files"
              ls -lrtha