name: Multiple Job Worklow
on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Install cowsay and Execute command
              run:  |
                echo "Install Cowsay Program"
                sudo apt-get install cowsay -y

                echo "Execute Cowsay CMD"
                cowsay -f dragon "Run for cover, I am a DRAGON...RAWR" >> dragon.txt


            - name: Upload Artifact text file
              uses: actions/upload-artifact@v4
              with:
                name: dragon-text-file
                path: dragon.txt

    test:
        needs: build
        runs-on: ubuntu-latest
        steps: 
            - name: Download Artifact text file
              uses: actions/download-artifact@v8
              with:
                name: dragon-text-file 

            - name:  Test File existence
              run: | 
                echo "Test File Exists"
                grep -i "dragon" dragon.txt
  
    deploy:
        needs: [test]
        runs-on: ubuntu-latest
        steps:
          - name: Download Artifact text file
            uses: actions/download-artifact@v8
            with:
              name: dragon-text-file   

          - name: Sleep of 10 seconds
            run: |
              sleep 10
              echo "Read File"
              cat dragon.txt

              echo "List Repo Files"
              ls -lrtha