name: Workflow with env at jobs level

on: 
  #push
  workflow_dispatch: 
    

jobs:
    docker:
      env:
        CONTAINER_REGISTRY: docker.io
        DOCKER_USERNAME: dockerUserName
        DOCKER_IMAGE: imageName

      runs-on: ubuntu-latest
      steps:
          - name: Docker build
            run: docker build -t docker.io/$DOCKER_USERNAME/$DOCKER_IMAGE:latest

          - name: Docker login
            env:
              DOCKER_PASSWORD: s3cUrePaSsw0rd
            run: docker login --username=${{env.DOCKER_USERNAME}} --password=$DOCKER_PASSWORD

          - name: Docker Publish
            run: docker push ${{env.CONTAINER_REGISTRY}}/${{env.DOCKER_USERNAME}}/${{env.DOCKER_IMAGE}}:latest

    deploy:
      env:
        CONTAINER_REGISTRY: docker.io
        DOCKER_USERNAME: dockerUserName
        DOCKER_IMAGE: imageName 
      needs: docker
      runs-on: ubuntu-latest
      steps:
        - name: Docker run
          run: docker run -d -p 8080:80  ${{env.CONTAINER_REGISTRY}}/${{env.DOCKER_USERNAME}}/${{env.DOCKER_IMAGE}}:latest
