name: Exploring variables and workflows

on: 
    push

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Docker build
              env:
                CONTAINER_REGISTRY: docker.io
                DOCKER_USERNAME: dockerUserName
                DOCKER_IMAGE: imageName
              run: docker build -t docker.io/$DOCKER_USERNAME/$DOCKER_IMAGE:latest

            - name: Docker login
              env:
                DOCKER_USERNAME: dockerUserName
                DOCKER_PASSWORD: s3cUrePaSsw0rd
              run: docker login --username=${{env.DOCKER_USERNAME}} --password=$DOCKER_PASSWORD

            - name: Docker Publish
              env:
                CONTAINER_REGISTRY: docker.io
                DOCKER_USERNAME: dockerUserName
                DOCKER_IMAGE: imageName
              run: docker push ${{env.CONTAINER_REGISTRY}}/${{env.DOCKER_USERNAME}}/${{env.DOCKER_IMAGE}}:latest

    deploy:
        needs: docker
        runs-on: ubuntu-latest
        steps:
          - name: Docker run
            env:
              CONTAINER_REGISTRY: docker.io
              DOCKER_USERNAME: dockerUserName
              DOCKER_IMAGE: imageName 
            run: docker run -d -p 8080:80  ${{env.CONTAINER_REGISTRY}}/${{env.DOCKER_USERNAME}}/${{env.DOCKER_IMAGE}}:latest
